# Generated by Django 3.0.1 on 2019-12-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(max_length=100)),
                ('query_type', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=1000)),
            ],
        ),
    ]
