# Generated by Django 3.0.1 on 2019-12-23 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191223_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
