# Generated by Django 3.0.1 on 2019-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subject_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='query_string',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='result',
        ),
        migrations.AddField(
            model_name='subject',
            name='cityname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='citytype',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='inn',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ex',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='orgn',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='registration_date',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
