# Generated by Django 3.0.1 on 2019-12-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191223_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='orgn',
            new_name='ogrn',
        ),
    ]
