# Generated by Django 3.0.1 on 2019-12-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191223_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='request_time',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('query_string', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
        ),
    ]
