# Generated by Django 3.0.1 on 2019-12-23 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191223_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_time',
        ),
        migrations.AddField(
            model_name='subject',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
