# Generated by Django 3.0.1 on 2019-12-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191223_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Query',
        ),
    ]
